version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false  
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=testpass
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  logstash:
    image: logstash:8.7.1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
    environment:
      - xpack.security.enabled=false  
      - xpack.license.self_generated.type=basic      
    networks:
      - esnet      

  kibana:
    image: kibana:8.7.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - xpack.security.enabled=false  
      - xpack.license.self_generated.type=basic
    networks:
      - esnet
volumes:
  esdata:
    driver: local
networks:
  esnet:
    driver: bridge